#%RAML 0.8
---
title: <%= projectTitle %>
documentation:
  - title: <%= projectTitle %>
    content: <%= projectDescription %>
baseUri: https://api.devicestack.rackspace.com/{version}
version: v<%= apiVersion %>
mediaType: application/json
protocols: [ HTTPS ]

schemas:
  - Accepted: !include schema/accepted-full.json
/acceptances:
  !include raml/acceptances.raml
