displayName: Acceptance
post:
  description: Submit an *Accepted* announcement.
  body:
    application/json:
      schema: Accepted
      example: !include examples/accepted.json
  responses:
    202:
      headers:
        Content-Type:
          description: |
            Describes the content type of the body of the response.
          example: application/json
        Content-Location:
          description: |
            Used to send the URI that can be monitored to determine what the
            final status of the *POST* operation is.

            This is the known as the *status monitor* location. Once the operation
            is successfully created, a *GET* on the
            [status monitor](http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.2.3)
            location will respond with a redirect 303 to the final location
            of the created resource.
          type: string
          example: https://example.com/acceptances/2702096010
          required: true
        Retry-After:
          description: |
            Provides an estimated completion time in seconds for the resource.

            The client should wait at least this long before checking the
            *status monitor* location as indicated in the *Content-Location*
            header.
          type: integer
      body:
        application/json:
          schema: Accepted
          example: !include schema/accepted.json
